import fs from 'node:fs';
import path from 'node:path';
import archiver from 'archiver';
import { getProduct } from './catalog.js';

// Package a forged product into a ready-to-upload .zip for external
// marketplaces (Etsy, Gumroad, Creative Market, ...). The bundle contains:
//   - template.pdf     the actual sellable file
//   - preview.svg      the thumbnail/mockup
//   - listing.txt      copy/paste title, description, tags, price
//   - listing.json     the same, machine-readable
export async function exportProduct(slug, { outDir = path.resolve('output', '_packages') } = {}) {
  const product = getProduct(slug);
  if (!product) throw new Error(`No product with slug "${slug}". Run "forge list" to see products.`);

  const srcDir = path.resolve('output', slug);
  fs.mkdirSync(outDir, { recursive: true });
  const zipPath = path.join(outDir, `${slug}.zip`);

  const listingTxt = renderListingText(product);
  fs.writeFileSync(path.join(srcDir, 'listing.txt'), listingTxt);
  fs.writeFileSync(
    path.join(srcDir, 'listing.json'),
    JSON.stringify(
      {
        title: product.title,
        description: product.description,
        tags: product.tags,
        price: product.price,
        category: product.category,
      },
      null,
      2
    )
  );

  await zipDir(srcDir, zipPath);
  return { zipPath, listingTxt };
}

function renderListingText(p) {
  return [
    `TITLE`,
    p.title,
    ``,
    `PRICE`,
    `$${Number(p.price).toFixed(2)}`,
    ``,
    `DESCRIPTION`,
    p.description,
    ``,
    `TAGS (comma-separated)`,
    p.tags.join(', '),
    ``,
    `CATEGORY`,
    p.category,
    ``,
    `FILES`,
    `- template.pdf  (the deliverable buyers download)`,
    `- preview.svg   (listing thumbnail / mockup)`,
    ``,
    `Generated by PDF Forge (${p.engine} engine) on ${new Date(p.createdAt).toDateString()}.`,
  ].join('\n');
}

function zipDir(srcDir, zipPath) {
  return new Promise((resolve, reject) => {
    const output = fs.createWriteStream(zipPath);
    const archive = archiver('zip', { zlib: { level: 9 } });
    output.on('close', () => resolve(zipPath));
    archive.on('error', reject);
    archive.pipe(output);
    // Only ship buyer-facing files, not internal product.json.
    for (const f of ['template.pdf', 'preview.svg', 'listing.txt', 'listing.json']) {
      const fp = path.join(srcDir, f);
      if (fs.existsSync(fp)) archive.file(fp, { name: f });
    }
    archive.finalize();
  });
}
